import {Product} from '@models/product.interface';

export const productsList: Product[] = [
  {
    id: 1,
    title: 'Apple',
    name: 'Organic Fuji Apple',
    type: 'fruit',
    countryOfOrigin: 'USA',
    nutritionalValues: {
      calories: 95,
      carbohydrates: 25,
      protein: 0.5,
      fat: 0.3,
      fiber: 4.4,
      sugar: 19,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: false,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: ['USDA Organic'],
    },
    unit: 'unit',
    priceByUnit: 0.99,
    salePriceByUnit: 0.89,
    rating: 4.7,
  },
  {
    id: 2,
    title: 'Banana',
    name: 'Fair Trade Banana',
    type: 'fruit',
    countryOfOrigin: 'Ecuador',
    nutritionalValues: {
      calories: 105,
      carbohydrates: 27,
      protein: 1.3,
      fat: 0.3,
      fiber: 3.1,
      sugar: 14,
    },
    sustainability: {
      fairTrade: true,
      organic: false,
      local: false,
      carbonFootprint: 0.5,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Keep refrigerated'],
      certifications: ['Fair Trade Certified'],
    },
    unit: 'unit',
    priceByUnit: 0.59,
    salePriceByUnit: null,
    rating: 4.5,
  },
  {
    id: 3,
    title: 'Carrot',
    name: 'Organic Carrot',
    type: 'vegetable',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 41,
      carbohydrates: 10,
      protein: 0.9,
      fat: 0.2,
      fiber: 2.8,
      sugar: 4.7,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: true,
      carbonFootprint: 0.2,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: ['EU Organic'],
    },
    unit: 'kg',
    priceByUnit: 1.2,
    salePriceByUnit: null,
    rating: 4.6,
  },
  {
    id: 4,
    title: 'Broccoli',
    name: 'Fresh Broccoli Head',
    type: 'vegetable',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 55,
      carbohydrates: 11,
      protein: 3.7,
      fat: 0.6,
      fiber: 3.8,
      sugar: 2.2,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.4,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Consume within 3 days'],
      certifications: [],
    },
    unit: 'head',
    priceByUnit: 1.5,
    salePriceByUnit: null,
    rating: 4.4,
  },
  {
    id: 5,
    title: 'Strawberry',
    name: 'Organic Strawberries',
    type: 'fruit',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 33,
      carbohydrates: 8,
      protein: 0.7,
      fat: 0.3,
      fiber: 2.0,
      sugar: 4.9,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: true,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Highly perishable'],
      certifications: ['EU Organic'],
    },
    unit: 'kg',
    priceByUnit: 4.5,
    salePriceByUnit: null,
    rating: 4.8,
  },
  {
    id: 6,
    title: 'Potato',
    name: 'Local White Potato',
    type: 'vegetable',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 77,
      carbohydrates: 17,
      protein: 2.0,
      fat: 0.1,
      fiber: 2.2,
      sugar: 0.8,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: true,
      carbonFootprint: 0.2,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 0.99,
    salePriceByUnit: null,
    rating: 4.3,
  },
  {
    id: 7,
    title: 'Orange',
    name: 'Organic Valencia Orange',
    type: 'fruit',
    countryOfOrigin: 'Spain',
    nutritionalValues: {
      calories: 62,
      carbohydrates: 15.4,
      protein: 1.2,
      fat: 0.2,
      fiber: 3.1,
      sugar: 12.2,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: false,
      carbonFootprint: 0.4,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: ['EU Organic'],
    },
    unit: 'unit',
    priceByUnit: 0.85,
    salePriceByUnit: null,
    rating: 4.6,
  },
  {
    id: 8,
    title: 'Spinach',
    name: 'Fresh Baby Spinach',
    type: 'vegetable',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 23,
      carbohydrates: 3.6,
      protein: 2.9,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Keep refrigerated'],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 2.5,
    salePriceByUnit: 2.2,
    rating: 4.5,
  },
  {
    id: 9,
    title: 'Blueberry',
    name: 'Wild Blueberries',
    type: 'fruit',
    countryOfOrigin: 'Canada',
    nutritionalValues: {
      calories: 57,
      carbohydrates: 14.5,
      protein: 0.7,
      fat: 0.3,
      fiber: 2.4,
      sugar: 9.7,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.6,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Highly perishable'],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 6.0,
    salePriceByUnit: 5.5,
    rating: 4.9,
  },
  {
    id: 10,
    title: 'Tomato',
    name: 'Heirloom Tomato',
    type: 'vegetable',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 18,
      carbohydrates: 3.9,
      protein: 0.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: true,
      carbonFootprint: 0.2,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 2.0,
    salePriceByUnit: 1.8,
    rating: 4.4,
  },
  {
    id: 11,
    title: 'Avocado',
    name: 'Hass Avocado',
    type: 'fruit',
    countryOfOrigin: 'Mexico',
    nutritionalValues: {
      calories: 160,
      carbohydrates: 8.5,
      protein: 2.0,
      fat: 14.7,
      fiber: 6.7,
      sugar: 0.7,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.9,
    },
    notices: {
      allergens: ['None'],
      warnings: ['High in fat'],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 1.5,
    salePriceByUnit: 1.3,
    rating: 4.7,
  },
  {
    id: 12,
    title: 'Cucumber',
    name: 'English Cucumber',
    type: 'vegetable',
    countryOfOrigin: 'Netherlands',
    nutritionalValues: {
      calories: 16,
      carbohydrates: 3.6,
      protein: 0.7,
      fat: 0.1,
      fiber: 0.5,
      sugar: 1.7,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: false,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 1.2,
    salePriceByUnit: 1.0,
    rating: 4.3,
  },
  {
    id: 13,
    title: 'Mango',
    name: 'Organic Mango',
    type: 'fruit',
    countryOfOrigin: 'India',
    nutritionalValues: {
      calories: 99,
      carbohydrates: 25,
      protein: 1.4,
      fat: 0.6,
      fiber: 2.6,
      sugar: 23,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: false,
      carbonFootprint: 0.8,
    },
    notices: {
      allergens: ['None'],
      warnings: ['May cause allergic reactions in sensitive individuals'],
      certifications: ['USDA Organic'],
    },
    unit: 'unit',
    priceByUnit: 1.5,
    salePriceByUnit: 1.3,
    rating: 4.6,
  },
  {
    id: 14,
    title: 'Pineapple',
    name: 'Fresh Pineapple',
    type: 'fruit',
    countryOfOrigin: 'Costa Rica',
    nutritionalValues: {
      calories: 82,
      carbohydrates: 22,
      protein: 0.9,
      fat: 0.2,
      fiber: 2.3,
      sugar: 16.3,
    },
    sustainability: {
      fairTrade: true,
      organic: false,
      local: false,
      carbonFootprint: 0.7,
    },
    notices: {
      allergens: ['None'],
      warnings: ['High acidity may affect sensitive stomachs'],
      certifications: ['Fair Trade Certified'],
    },
    unit: 'unit',
    priceByUnit: 2.5,
    salePriceByUnit: 2.2,
    rating: 4.7,
  },
  {
    id: 15,
    title: 'Watermelon',
    name: 'Seedless Watermelon',
    type: 'fruit',
    countryOfOrigin: 'Spain',
    nutritionalValues: {
      calories: 46,
      carbohydrates: 11.5,
      protein: 0.9,
      fat: 0.2,
      fiber: 0.6,
      sugar: 9.4,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: true,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Highly perishable'],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 0.8,
    salePriceByUnit: 0.7,
    rating: 4.5,
  },
  {
    id: 16,
    title: 'Kiwi',
    name: 'Green Kiwi',
    type: 'fruit',
    countryOfOrigin: 'New Zealand',
    nutritionalValues: {
      calories: 42,
      carbohydrates: 10.1,
      protein: 0.8,
      fat: 0.4,
      fiber: 2.1,
      sugar: 6.7,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.5,
    },
    notices: {
      allergens: ['None'],
      warnings: ['May cause allergic reactions in sensitive individuals'],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 0.6,
    salePriceByUnit: null,
    rating: 4.4,
  },
  {
    id: 17,
    title: 'Papaya',
    name: 'Organic Papaya',
    type: 'fruit',
    countryOfOrigin: 'Brazil',
    nutritionalValues: {
      calories: 62,
      carbohydrates: 16,
      protein: 0.7,
      fat: 0.4,
      fiber: 2.5,
      sugar: 11,
    },
    sustainability: {
      fairTrade: false,
      organic: true,
      local: false,
      carbonFootprint: 0.6,
    },
    notices: {
      allergens: ['None'],
      warnings: ['May cause allergic reactions in sensitive individuals'],
      certifications: ['USDA Organic'],
    },
    unit: 'unit',
    priceByUnit: 2.0,
    salePriceByUnit: 1.8,
    rating: 4.6,
  },
  {
    id: 18,
    title: 'Peach',
    name: 'Fresh Peach',
    type: 'fruit',
    countryOfOrigin: 'Italy',
    nutritionalValues: {
      calories: 51,
      carbohydrates: 12.4,
      protein: 1.2,
      fat: 0.3,
      fiber: 1.9,
      sugar: 10.9,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: true,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Highly perishable'],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 0.9,
    salePriceByUnit: 0.8,
    rating: 4.5,
  },
  {
    id: 19,
    title: 'Pear',
    name: 'Bartlett Pear',
    type: 'fruit',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 101,
      carbohydrates: 27,
      protein: 0.6,
      fat: 0.3,
      fiber: 5.5,
      sugar: 17,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: true,
      carbonFootprint: 0.2,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 1.0,
    salePriceByUnit: null,
    rating: 4.4,
  },
  {
    id: 20,
    title: 'Plum',
    name: 'Red Plum',
    type: 'fruit',
    countryOfOrigin: 'France',
    nutritionalValues: {
      calories: 30,
      carbohydrates: 7.5,
      protein: 0.5,
      fat: 0.2,
      fiber: 0.9,
      sugar: 6.6,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.4,
    },
    notices: {
      allergens: ['None'],
      warnings: [],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 0.7,
    salePriceByUnit: null,
    rating: 4.3,
  },
  {
    id: 21,
    title: 'Cherry',
    name: 'Sweet Cherry',
    type: 'fruit',
    countryOfOrigin: 'USA',
    nutritionalValues: {
      calories: 87,
      carbohydrates: 22,
      protein: 1.4,
      fat: 0.3,
      fiber: 3,
      sugar: 17.7,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.5,
    },
    notices: {
      allergens: ['None'],
      warnings: ['Highly perishable'],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 5.0,
    salePriceByUnit: 4.5,
    rating: 4.8,
  },
  {
    id: 22,
    title: 'Grape',
    name: 'Red Seedless Grape',
    type: 'fruit',
    countryOfOrigin: 'Spain',
    nutritionalValues: {
      calories: 62,
      carbohydrates: 16,
      protein: 0.6,
      fat: 0.3,
      fiber: 1,
      sugar: 15,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.4,
    },
    notices: {
      allergens: ['None'],
      warnings: ['May contain sulfites'],
      certifications: [],
    },
    unit: 'kg',
    priceByUnit: 3.0,
    salePriceByUnit: 2.7,
    rating: 4.6,
  },
  {
    id: 23,
    title: 'Lemon',
    name: 'Fresh Lemon',
    type: 'fruit',
    countryOfOrigin: 'Portugal',
    nutritionalValues: {
      calories: 29,
      carbohydrates: 9.3,
      protein: 1.1,
      fat: 0.3,
      fiber: 2.8,
      sugar: 2.5,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: true,
      carbonFootprint: 0.2,
    },
    notices: {
      allergens: ['None'],
      warnings: ['High acidity'],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 0.5,
    salePriceByUnit: 0.4,
    rating: 4.5,
  },
  {
    id: 24,
    title: 'Lime',
    name: 'Key Lime',
    type: 'fruit',
    countryOfOrigin: 'Mexico',
    nutritionalValues: {
      calories: 30,
      carbohydrates: 11,
      protein: 0.7,
      fat: 0.2,
      fiber: 3,
      sugar: 1.1,
    },
    sustainability: {
      fairTrade: false,
      organic: false,
      local: false,
      carbonFootprint: 0.3,
    },
    notices: {
      allergens: ['None'],
      warnings: ['High acidity'],
      certifications: [],
    },
    unit: 'unit',
    priceByUnit: 0.6,
    salePriceByUnit: 0.5,
    rating: 4.4,
  },
];
